require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vender/**/*

Layout/LineLength:
  Max: 120
  AutoCorrect: true
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - "app/api/**/*"
    - "config/**/*.rb"
    - "db/**/*.rb"
    - "lib/**/*.rake"
    - "spec/**/*"
Metrics/ModuleLength:
  CountComments: false
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/BlockDelimiters:
  Exclude:
    - "spec/**/*_spec.rb"
Style/CaseLikeIf:
  Enabled: true
Style/ClassEqualityComparison:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/FormatStringToken:
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: false # Disabled https://github.com/JuanitoFatas/fast-ruby#hashfetch-with-argument-vs-hashfetch--block-code
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/SlicingWithRange:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: true
Style/StringConcatenation:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/KeywordParametersOrder:
  Enabled: true
Style/Lambda:
  EnforcedStyle: literal
Style/OptionalBooleanParameter:
  Enabled: true
Style/SymbolArray:
  MinSize: 3
Style/WordArray:
  MinSize: 3

# Performance specific from rubocop-performance
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Performance/Sum:
  Enabled: true

# Rails specific from rubocop-rails
Rails:
  Enabled: true
Rails/BulkChangeTable:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Exclude:
    - "app/controllers/concerns/**/*.rb"
Rails/Output:
  Enabled: false
Rails/OutputSafety:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*.rb"
    - "spec/factories/*.rb"

# Rspec specific
RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/policies/**/*_spec.rb"
RSpec/Focus:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - "spec/db/**/*_spec.rb"
    - "spec/requests/**/*_spec.rb"
